version: "3"

services:
    api:
        build:
            dockerfile: Dockerfile
            context: api
        ports:
            - "5000:5000"

    web:
        build:
            dockerfile: Dockerfile
            context: web
        ports:
            - "3000:3000"
        depends_on:
            - api

